### ISSUE TITLE
Exception in people.py: profile_photo may be NoneType

### ISSUE THREAD

**Issue by obscurerichard** [freezingsaddles/freezing-web#196]
```freezing-web         | [2020-03-22 01:30:42,768] ERROR in app: Exception on /people/5255929 [GET]
freezing-web         | Traceback (most recent call last):
freezing-web         |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
freezing-web         |     response = self.full_dispatch_request()
freezing-web         |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
freezing-web         |     rv = self.handle_user_exception(e)
freezing-web         |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
freezing-web         |     reraise(exc_type, exc_value, tb)
freezing-web         |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
freezing-web         |     raise value
freezing-web         |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
freezing-web         |     rv = self.dispatch_request()
freezing-web         |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
freezing-web         |     return self.view_functions[rule.endpoint](**req.view_args)
freezing-web         |   File "/app/freezing/web/views/people.py", line 78, in people_show_person
freezing-web         |     if our_user.profile_photo and not str.startswith(our_user.profile_photo, "http"):
freezing-web         | AttributeError: 'NoneType' object has no attribute 'profile_photo'
```

**Comment by obscurerichard** [comment]
Resolved in https://github.com/freezingsaddles/freezing-web/pull/239

**Comment by obscurerichard** [comment]
Resolved in https://github.com/freezingsaddles/freezing-web/pull/239
