### ISSUE TITLE
Instagram cache profile exception

### ISSUE THREAD

**Issue by obscurerichard** [freezingsaddles/freezing-web#197]
I thought we no longer had Instagram support, but we are getting exceptions related to this in the log currently:

```
freezing-web         | [2020-03-21 23:22:05,292] ERROR in app: Exception on /photos/1168797630991328637_1159135920.jpg [GET]
freezing-web         | Traceback (most recent call last):
freezing-web         |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
freezing-web         |     response = self.full_dispatch_request()
freezing-web         |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
freezing-web         |     rv = self.handle_user_exception(e)
freezing-web         |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
freezing-web         |     reraise(exc_type, exc_value, tb)
freezing-web         |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
freezing-web         |     raise value
freezing-web         |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
freezing-web         |     rv = self.dispatch_request()
freezing-web         |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
freezing-web         |     return self.view_functions[rule.endpoint](**req.view_args)
freezing-web         |   File "/app/freezing/web/views/photos.py", line 20, in instagram_photo
freezing-web         |     photopath = insta.photo_cache_path(uid, resolution=insta.STANDARD)
freezing-web         |   File "/app/freezing/web/utils/insta.py", line 35, in photo_cache_path
freezing-web         |     cache_dir = config.INSTAGRAM_CACHE_DIR
```

**Comment by merlinorg** [comment]
OBE
