### ISSUE TITLE
Exception in all/tracks.geojson - suspected MySQL 8 incompatibility with SQLAlchemy 

### ISSUE THREAD

**Issue by obscurerichard** [freezingsaddles/freezing-web#295]
While doing some exploratory testing on freezingsaddles.org for [Bump geojson from 2.5.0 to 3.1.0  #272](https://github.com/freezingsaddles/freezing-web/pull/272)  I got an exception `pymysql.err.OperationalError: (1305, 'FUNCTION freezing.AsBinary does not exist')` - this came from deep in the guts of `pmysql` and `sqlalchemy` and . We need to triage this more and figure out what upgrades we need to do to get around this, preferably _before_ the start of the 2025 season. This might extend into `freezing-sync` as well, since that uses some geometry related stuff too.

This is an unintended consequence of #281 . 

@obscurerichard has limited knowledge of the MySQL geospatial facilities and the supporting libraries so debugging this may be a challenge... also the tests for this area of freezing-web, freezing-model, and freezing-sync are almost non-existent.

## Leads

* [sqlAlchemy converts geometry to byte using ST_AsBinary](https://stackoverflow.com/questions/37031377/sqlalchemy-converts-geometry-to-byte-using-st-asbinary) - has an [answer](https://stackoverflow.com/a/63295058/424301) talking about subclassing `BaseGeometry` to override  `as_binary = 'ST_asText'
* [Working with Geospatial Features in MySQL](https://planetscale.com/blog/geospatial-features-mysql) - a primer on MySQL 8 geospatial facilities, including data types and functions
* [Why some spatial functions does not exists on my mysql server?](https://stackoverflow.com/questions/60377271/why-some-spatial-functions-does-not-exists-on-my-mysql-server) - see [this answer](https://stackoverflow.com/a/60377521/424301) for a list of the functions that went away.
* [creof/doctrine-2-spatial PR 196 that fixes MySQL 8 compatibility with AsBinary](https://github.com/creof/doctrine2-spatial/pull/196/files)
* [Migrate to GeoAlchemy 2](https://geoalchemy-2.readthedocs.io/en/latest/migrate.html#migrate)

## Solution options

* If we're really lucky, disable functionality that depends on this, if it has minimal impact (high risk, low effort)
* Find specific incompatibilities in ancient libraries and patch them (low risk, medium effort)
* Add compatibility functions that map names to modern MySQL names (low risk, medium effort) such as 
* Upgrade to modern, supported SQLAlchemy and GeoAlchemy libraries (medium risk, high effort)
 
 ## Security considerations
 
 We might consider restricting who can call `all/tracks.geojson`  and the related teams .geojson. We definitely should verify that there's no personally identifying information about the athletes in it. It looks like those geojson files could be used to build an awesome heatmap, but there's nothing in the code today that uses these.
 
 ## Error logs

```
[2024-11-30 05:17:16,421] ERROR in app: Exception on /api/all/tracks.geojson [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1305, 'FUNCTION freezing.AsBinary does not exist')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/freezing/web/utils/auth.py", line 68, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/app/freezing/web/views/api.py", line 245, in geo_tracks_all
    return _geo_tracks(start_date=start_date, end_date=end_date)
  File "/app/freezing/web/views/api.py", line 209, in _geo_tracks
    for ride_track in q:
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1305, 'FUNCTION freezing.AsBinary does not exist')
[SQL: SELECT AsBinary(ride_tracks.gps_track) AS ride_tracks_gps_track, ride_tracks.ride_id AS ride_tracks_ride_id, ride_tracks.elevation_stream AS ride_tracks_elevation_stream, ride_tracks.time_stream AS ride_tracks_time_stream
FROM ride_tracks INNER JOIN rides ON rides.id = ride_tracks.ride_id INNER JOIN athletes ON athletes.id = rides.athlete_id
WHERE false = 1]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
Unable to set attribute activity_types on entity <Club id=122521 name='REI' resource_state=2>
Unable to set attribute activity_types_icon on entity <Club id=122521 name='REI' resource_state=2>
Unable to set attribute dimensions on entity <Club id=122521 name='REI' resource_state=2>
Unable to set attribute localized_sport_type on entity <Club id=122521 name='REI' resource_state=2>
Unable to set attribute activity_types on entity <Club id=1324205 name='Freezing Saddles 2025' resource_state=2>
Unable to set attribute activity_types_icon on entity <Club id=1324205 name='Freezing Saddles 2025' resource_state=2>
Unable to set attribute dimensions on entity <Club id=1324205 name='Freezing Saddles 2025' resource_state=2>
Unable to set attribute localized_sport_type on entity <Club id=1324205 name='Freezing Saddles 2025' resource_state=2>
```

**Comment by merlinorg** [comment]
@obscurerichard does *anything* actually use the geo data? It appeared completely unused to me.

**Comment by obscurerichard** [comment]
There's 2 endpoints that use the geojson data:

1. https://freezingsaddles.org/api/all/tracks.geojson
2. `https://freezingsaddles.org/api/teams/<int:team_id>/tracks.geojson` for [example with the main 2025 team](https://freezingsaddles.org/api/teams/1324205/tracks.geojson) - [Freezing Saddles 2025](https://www.strava.com/clubs/1324205)

See the code in [freezing.web.views.api]()https://github.com/freezingsaddles/freezing-web/blob/8b773a2a868812269795d14c0d7cc305f9993662/freezing/web/views/api.py#L184-L256 nothing else in the `freezing-web`pulls on this library.

So from that standpoint we could remove the geojson library and the 2 API calls and have `freezing-web` be clean. I think you are right about these not being in use now. However, I think I understand _what they **could** be used for_ and it's pretty exciting: [Generate heatmaps for team rides #297](https://github.com/freezingsaddles/freezing-web/issues/297).

I'm actually far more worried about the code paths in `freezing-sync` that use geospatial data. Those paths are **not getting exercised** properly before the competition start. I'm creating [Triage MySQL 8 geospatial query compatibility with freezing-sync #56](https://github.com/freezingsaddles/freezing-sync/issues/56) to track that.
