### ISSUE TITLE
Handle RateLimitExceeded errors

### ISSUE THREAD

**Issue by hozn** [freezingsaddles/freezing-web#39]
We should immediately stop our sync tasks if/when we hit RateLimitExceeded.  (Maybe this is already true, but needs to be confirmed.)  Additionally, we should probably ensure our cron is setup so that we don't incur the error again at next run.  E.g. maybe move ride sync to 5 minutes.

What we really need is to implement the webhook API.

```
Traceback (most recent call last):
  File "/home/freezingsaddles/sites/freezingsaddles.com/env/bin/bafs-sync", line 11, in <module>
    load_entry_point('bafs', 'console_scripts', 'bafs-sync')()
  File "/home/freezingsaddles/sites/freezingsaddles.com/freezingsaddles/bafs/scripts/sync_rides.py", line 177, in main
    SyncRides().run()
  File "/home/freezingsaddles/sites/freezingsaddles.com/freezingsaddles/bafs/scripts/__init__.py", line 105, in run
    self.execute(options, args)
  File "/home/freezingsaddles/sites/freezingsaddles.com/freezingsaddles/bafs/scripts/sync_rides.py", line 81, in execute
    self._write_rides(start, end_date, athlete=athlete, rewrite=options.rewrite)
  File "/home/freezingsaddles/sites/freezingsaddles.com/freezingsaddles/bafs/scripts/sync_rides.py", line 94, in _write_rides
    exclude_keywords=app.config.get('BAFS_EXCLUDE_KEYWORDS'))
  File "/home/freezingsaddles/sites/freezingsaddles.com/freezingsaddles/bafs/data.py", line 228, in list_rides
    filtered_rides = [a for a in activities if
  File "/home/freezingsaddles/sites/freezingsaddles.com/freezingsaddles/bafs/data.py", line 228, in <listcomp>
    filtered_rides = [a for a in activities if
  File "/home/freezingsaddles/sites/freezingsaddles.com/stravalib/stravalib/client.py", line 1587, in __next__
    return self.next()
  File "/home/freezingsaddles/sites/freezingsaddles.com/stravalib/stravalib/client.py", line 1593, in next
    self._fill_buffer()
  File "/home/freezingsaddles/sites/freezingsaddles.com/stravalib/stravalib/client.py", line 1564, in _fill_buffer
    raw_results = self.result_fetcher(page=self._page, per_page=self.per_page)
  File "/home/freezingsaddles/sites/freezingsaddles.com/stravalib/stravalib/protocol.py", line 241, in get
    return self._request(url, params=params, check_for_errors=check_for_errors, use_webhook_server=use_webhook_server)
  File "/home/freezingsaddles/sites/freezingsaddles.com/stravalib/stravalib/protocol.py", line 171, in _request
    self.rate_limiter(raw.headers)
  File "/home/freezingsaddles/sites/freezingsaddles.com/stravalib/stravalib/util/limiter.py", line 235, in __call__
    r(args)
  File "/home/freezingsaddles/sites/freezingsaddles.com/stravalib/stravalib/util/limiter.py", line 96, in __call__
    self._check_limit_rates(limit)
  File "/home/freezingsaddles/sites/freezingsaddles.com/stravalib/stravalib/util/limiter.py", line 109, in _check_limit_rates
    self._raise_rate_limit_exception(limit['limit'], limit['time'])
  File "/home/freezingsaddles/sites/freezingsaddles.com/stravalib/stravalib/util/limiter.py", line 123, in _raise_rate_limit_exception
    .format(limit_rate, timeout))
stravalib.exc.RateLimitExceeded: Rate limit of 900 exceeded. Try again in 600 seconds.
```

**Comment by obscurerichard** [comment]
I think that the implementation of #40 (which I think is really and truly put to bed) resolved this. Can you help confirm @hozn ?

**Comment by obscurerichard** [comment]
So #40 did resolve this and https://github.com/freezingsaddles/freezing-nq is the embodiment of this ticket. Closing!
